In [ ]:
chinese = [55,33,70,49]
jewish = [141,145,139,161]

In [1]:
import numpy as np
import scipy.stats

data = np.array([[55, 141],
                 [33, 145],
                 [70, 139],
                 [49, 161]])

totals = np.sum(data, axis=0)
fracs = data / totals
deltas = fracs @ [1., -1.]
std_errs = np.sqrt(np.sum(fracs * (1. - fracs) / totals, axis=1))
wald_stats = deltas / std_errs
p_values = 2. * scipy.stats.norm.cdf(-np.abs(wald_stats))
bonferroni_p_values = np.minimum(p_values.size * p_values, 1.)

In [4]:
totals

array([207, 586])

In [5]:
fracs

array([[0.26570048, 0.24061433],
       [0.15942029, 0.24744027],
       [0.33816425, 0.23720137],
       [0.23671498, 0.27474403]])

In [6]:
deltas

array([ 0.02508615, -0.08801998,  0.10096289, -0.03802905])

In [7]:
std_errs

array([0.03541663, 0.0310667 , 0.0372823 , 0.03482655])

In [8]:
wald_stats


array([ 0.70831559, -2.833258  ,  2.70806492, -1.09195567])

In [9]:
p_values

array([0.4787493 , 0.00460762, 0.00676768, 0.27485259])

In [10]:
bonferroni_p_values

array([1.        , 0.01843047, 0.02707071, 1.        ])

In [2]:
import numpy as np
for obs in [55,33,70,49]:
    print(obs * np.log10(obs/51.75))

1.4548784450908678
-6.448081670285242
9.183138011971103
-1.1619994309216437


In [3]:
a = 1.4548784450908678 -6.448081670285242 + 9.183138011971103 -1.1619994309216437
a

3.027935355855085

In [5]:
(141 + 145 + 139 + 161)/4

146.5

In [7]:
for obs in [141, 145, 139, 161]:
    print(obs * np.log10(obs/146.5))

-2.343210196899519
-0.648095255997241
-3.172372596608611
6.599108466017149


In [8]:


-2.343210196899519 -0.648095255997241 -3.172372596608611 + 6.599108466017149

0.4354304165117773